blog_project/mysite/blog/urls.py
from django.urls import path, re_path
from blog import views

app_name = 'blog'
urlpatterns = [
    path('',views.PostListView.as_view(),name='post_list'),
    path('about',views.AboutView.as_view(),name="about"),
    path('post/<int:pk>',views.PostDetailView.as_view(),name='post_detail'),
    path('post/new',views.PostCreateView.as_view(),name='post_new'),
    path('post/<int:pk>/edit/',views.PostUpdateView.as_view(),name='post_edit'),
    path('post/<int:pk>/remove',views.PostDeleteView.as_view(),name='post_remove'),
    path('drafts/',views.DraftListView.as_view(),name='post_draft_list'),
    path('post/<int:pk>/comment/',views.add_comment_to_post,name='add_comment_to_post'),
    path('comment/<int:pk>/approve/',views.comment_approve,name='comment_approve'),
    path('comment/<int:pk>/delete',views.comment_remove,name='comment_remove'),
    path('post/<int:pk>/publish/',views.post_publish,name='post_publish')
]

blog_project/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from blog import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('blogs.urls'))
]

blog_project/mysite/blog/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse

# Create your models here.


class Post(models.Model):

    author = models.ForeignKey('auth.User',on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    text = models.TextField()
    create_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True,null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()
    
    def approve_comments(self):

        return self.comments.filter(approved_comment=True)

    def get_absolute_url(self):
        return reverse('blog:post_detail',kwargs={'pk':self.pk})
    
    def __str__(self):

        return self.title


class Comment(models.Model):
    post = models.ForeignKey('blog.Post',related_name='comments',on_delete=models.CASCADE)
    author = models.CharField(max_length=200)
    text = models.TextField()
    create_date = models.DateTimeField(default=timezone.now)
    approved_comment = models.BooleanField(default=False)

    def get_absolute_url(self):
        return reverse('blog:post_list')
    
    def approve(self):

        self.approved_comment = True
        self.save()
    
    def __str__(self):
    
        return self.text
    
    

blog_project/mysite/blog/forms.py
from django import forms
from blog.models import Comment, Post

class PostForm(forms.ModelForm):

    class Meta():

        model = Post
        fields = ('author','title','text')
        widgets = {
            'title':forms.TextInput(attrs={'class':'textinputlclass'}),
            'text':forms.Textarea(attrs={'class':'editable medium-editor-textarea postcontent'})

        }

class CommentForm(forms.ModelForm):

    class Meta():
        model = Comment
        fields = ('author','text')

        widgets = {
            'author':forms.TextInput(attrs={'class':'textinputclass'}),
            'text':forms.Textarea(attrs={'class':'editable medium-editor-textarea '})
        }

blog_project/mysite/blog/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.utils import timezone
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import (TemplateView,ListView,UpdateView,DetailView,CreateView,DeleteView)

from blog.forms import PostForm,CommentForm
from blog.models import Post,Comment
# Create your views here.
class AboutView(TemplateView):
    template_name = 'about.html'


class PostListView(ListView):
    model = Post

    def get_queryset(self):
        return Post.objects.filter(published_date__lte=timezone.now()).order_by('-published_date')

class PostDetailView(DetailView):
    model = Post


class PostCreateView(LoginRequiredMixin,CreateView):
    login_url = '/login/'
    redirect_field_name = 'blog/post_detail.html'

    form_class = PostForm
    model = Post

class PostUpdateView(LoginRequiredMixin,UpdateView):
    login_url = '/login/'
    redirect_field_name = 'blog/post_detail.html'

    form_class = PostForm
    model = Post

class PostDeleteView(LoginRequiredMixin,DeleteView):
    model = Post
    success_url = reverse_lazy('blog:post_list')


class DraftListView(LoginRequiredMixin,ListView):

    model = Post
    login_url = '/login/'
    redirect_field_name = 'blog/post_list.html'

    def get_queryset(self):
        return Post.objects.filter(published_date__isnull=True).order_by('-create_date')

@login_required
def post_publish(request,pk):

    post = get_object_or_404(Post,pk=pk)
    post.publish()
    return redirect('blog:post_detail',pk=pk)


@login_required
def add_comment_to_post(request,pk):
    post = get_object_or_404(Post,pk=pk)

    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.save()
            return redirect('blog:post_detail',pk=post.pk)
    else:
        form = CommentForm()
    
    return render(request,'blog/comment_form.html',{'form':form})

@login_required
def comment_approve(request,pk):

    comment = get_object_or_404(Comment,pk=pk)
    comment.approve()

    return redirect('blog:post_detail',pk=comment.post.pk)


@login_required

def comment_remove(request,pk):
    comment = get_object_or_404(Comment,pk=pk)
    post_pk = comment.post.pk
    comment.delete()
    return redirect('blog:post_detail',pk=post_pk)
    

blog_project/mysite/blog/templates/blog/about.html
{% extends "base.html" %}

{% block content %}

<h1>About this company</h1>
<p>Thanks for checking it out</p>

{% endblock %}

blog_project/mysite/blog/templates/blog/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>

    {% comment %} Bootstrap {% endcomment %}
     <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    
     {% comment %} Medium Style Editor {% endcomment %}
    <script src="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/js/medium-editor.min.js"></script>
    <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/css/medium-editor.min.css" type="text/css" media="screen" charset="utf-8">
    
    {% comment %} Custom CSS {% endcomment %}
    <link rel="stylesheet" href = "{%static 'css/blog.css' %}">
    
    {% comment %} Fonts {% endcomment %}
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Gasoek+One&family=Quicksand&display=swap" rel="stylesheet">

</head>

<body class='loader'>
    
    {% comment %} Navbar {% endcomment %}
    <nav class="navbar navbar-default techfont custom-navbar">
        <div class='container'>

            <ul class='nav navbar-nav'>
                <li><a href="{% url 'blog:post_list'%}" class='navbar-brand bigbrand'>My Blog</a></li>
                <li><a href="{% url 'blog:about' %}">About</a></li>
                <li><a href="https://www.github.com/wereign">Github</a></li>
                <li><a href="https://www.linkedin.com">Linkedin</a></li>
            </ul>
            
            <ul class='nav navbar-nav'>
                {% if user.is_authenticated %}
                    <a class="nav-item nav-link" href="{% url 'blog:post_new' %}">New Post</a>
                    <a class="nav-item nav-link" href="{% url 'blog:post_draft_list' %}">Drafts</a>
                    <a class="nav-item nav-link" href="{% url 'logout' %}">Log out</a>
                    <a >Welcome: {{ user.username }}</a>
                {% else %}

                    <a class="nav-item nav-link" href="{% url 'login' %}" aria-label="Login">
                    <span class="fa fa-user" aria-hidden="true">Login</span></a>
                {% endif %}
                


            </ul>
        </div>

    </nav>

    {% comment %} Content Block {% endcomment %}
    <div class='content container'>
        <div class="row">
            <div class='content-md-8'>
                <div class='blog_posts'>
                    {% block content%}
                    {% endblock %}
                </div>
            </div>
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</html>

blog_project/mysite/blog/templates/blog/comment_form.html
{% extends "base.html" %}

{% block content %}
    <h1>New </h1>
    <form class='post-form' method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit" class='save btn btn-default'>
            Post Comment</button>

        <script>
            var editor = new MediumEditor('.editable');
        </script>

    </form>
{% endblock %}

blog_project/mysite/blog/templates/blog/post_confirm_delete.html
{% extends "base.html" %}
{% block content %}
    <form method="POST">
        {% csrf_token %}
        <p>Are you sure you want to delete {{object}}</p>
        <input type="submit" class='btn btn-danger' value='confirm'>
    </form>
{% endblock %}

blog_project/mysite/blog/templates/blog/post_detail.html
{% extends "base.html" %}

{% block content %}


    <h1 class='posttitle loader'>{{post.title}}</h1>

    {% if post.published_date %}
        <div class='date postdate'>
            {{post.published_date}}
        </div>
    {%else%}
        <a href="{% url 'blog:post_publish' pk=post.pk %}" class='btn btn-success'>Publish Post</a>
    {% endif %}

    <p class='postcontent'>{{post.title|safe|linebreaksbr}}</p>

    {% if user.is_authenticated%}
        <a href="{% url 'blog:post_edit' pk=post.pk %}" class='btn btn-primary'><span class='glyphicon glyphicon-pencil'>Edit</span></a>
        <a href="{% url 'blog:post_remove' pk=post.pk %}" class='btn btn-danger'><span class='glyphicon glyphicon-remove'>Remove</span></a>


         
    {% endif %}
    
    <hr>

    <a class='btn btn-primary btn-comment' href="{% url 'blog:add_comment_to_post' pk=post.pk %}">Add Comment</a>

    <div class='container'>
        {% for comment in post.comments.all %}
            <br>
             
            {% if user.is_authenticated or comment.approved_comment %}
             {{comment.created_date}}

              {% if not comment.approved_comment %}

              <a href="{% url 'blog:comment_remove' pk=comment.pk %}" class='btn btn-danger'><span class='glyphicon glyphicon-remove'>Remove</span></a>
                <a href="{% url 'blog:comment_approve' pk=comment.pk %}" class='btn btn-primary'><span class='glyphicon glyphicon-ok'>Approve</span></a>              
              {%endif%}
            

            <p>{{comment.text|safe|linebreaks}}</p>
            <p>Posted By: {{comment.author}}</p>
            {%endif%}
        {% endfor %}
    </div>
{% endblock %}

blog_project/mysite/blog/templates/blog/post_draft_list.html
{% extends "base.html" %}

{% block content %}
    {% for post in posts %}
        <div class='post'>
            <p class='date'>Created: {{post.create|date:'d-m-Y'}}</p>
            <h1><a href="{% url 'post_detail' pk=post.pk%}">{{post.title}}</a></h1>
            <p>{{post.text|truncatechars:200}}</p>
        </div>
    {% endfor %}
{% endblock %}

blog_project/mysite/blog/templates/blog/post_list.html
{% extends "base.html" %}

{% block content %}
<div class='centerstage'>
    {% for post in post_list %}
        <div class='post'>
            <h1><a href="{% url 'blog:post_detail' pk=post.pk %}">{{ post.title }}</a></h1>

            <div class='date'>
                <p>Published on {{post.published|date:"D M Y"}}</p>
            </div>

            <a href="{% url 'blog:post_detail' pk=post.pk %}">Comments: {{post.approve_comments.count}} </a>
        </div>
    {% endfor %}
</div>
{% endblock %}