social_media_project/simplesocial/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views


app_name = 'accounts'
urlpatterns = [
    path('login/',
         auth_views.LoginView.as_view(template_name='accounts/login.html')
         ,name='login'),
    path('logout/', auth_views.LogoutView.as_view(),name='logout'),
    path('signup/', views.SignUp.as_view() ,name='signup'),    
]

social_media_project/simplesocial/simplesocial/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.HomePage.as_view(),name='home'),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('accounts/', include("django.contrib.auth.urls")),  
]

social_media_project/simplesocial/accounts/models.py
from django.db import models
from django.contrib import auth

# Create your models here.
class User(auth.models.User,auth.models.PermissionsMixin):

    def __str__(self):
        return f"@{self.username}"

social_media_project/simplesocial/accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

class UserCreateForm(UserCreationForm):

    class Meta:
        fields = ('username','email','password1','password2')
        model = get_user_model()

    def __init__(self,*args,**kwargs):

        super().__init__(*args,**kwargs)
        self.fields['username'].label = 'Display Name'
        self.fields['email'].label = "Email Address"
        

                     

social_media_project/simplesocial/accounts/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView

from . import forms
# Create your views here.
class SignUp(CreateView):
    form_class = forms.UserCreateForm
    success_url = reverse_lazy('login')
    template_name = 'accounts/signup.html'

social_media_project/simplesocial/simplesocial/views.py
from django.views.generic import TemplateView
from django.urls import reverse_lazy


class HomePage(TemplateView):
    template_name = 'index.html'

social_media_project/simplesocial/accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block content %}
<div class="container">
    <h1>Login</h1>
    <form method="POST">
        {% csrf_token %}
        {%  bootstrap_form form %}
        <input type="submit" class="'btn btn-default" value="Login">
    </form>
</div>
{% endblock %}

social_media_project/simplesocial/accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block content %}
<div class="container">
    <h1>Sign Up</h1>
    <form method="POST">
        {% csrf_token %}
        {%  bootstrap_form form %}
        <input type="submit" class="'btn btn-default" value="Signup">
    </form>
</div>
{% endblock %}

social_media_project/simplesocial/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Star Social</title>

    <!-- Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">


    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'simplesocial/css/master.css'%}">
</head>
<body>
    <nav class="navbar mynav bg-dark" role="navigation" id="navbar">
        <div class="container">
            <a class='navbar-brand mynav' href="{% url 'home'%}">Star Social</a>
            
            {% if user.is_authenticated %}
            <a href="">Post</a>
            <a href="">Group</a>
            <a href="">Create Group</a>
            <a href="{% url 'accounts:logout' %}">Logout</a>
            
            {% else %}
            <a href="">Groups</a>
            <a href="{% url 'accounts:login' %}">Login</a>
            <a href="{% url 'accounts:signup' %}">Signup</a>
            {% endif %}
        </div>
    </nav>


    {% block content %}
    {% endblock %}

    <!-- Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</html>

social_media_project/simplesocial/templates/index.html
{% extends "base.html"%}
{% block content %}
<h1>Welcome to Star Social</h1>
{% endblock %}