CBV/advcbv/advcbv/urls.py
from django.contrib import admin
from django.urls import path
from basic_app.views import CBV,IndexView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('index/',CBV.as_view()),
    path('index2/',IndexView.as_view())
]

CBV/advcbv/basic_app/urls.py
from django.urls import path, re_path
from basic_app import views

app_name = 'basic_app'

urlpatterns = [
    path('',views.SchoolListView.as_view(),name='list'),
    path('<int:pk>/',views.SchoolDetailView.as_view(),name='detail'),
    path('create/',views.SchoolCreateView.as_view(),name='create'),
    path('update/<int:pk>/',views.SchoolUpdateView.as_view(),name='update'),
    path('delete/<int:pk>/',views.SchoolDeleteView.as_view(),name='delete'),

]

CBV/advcbv/basic_app/models.py
from django.db import models
from django.urls import reverse
# Create your models here.
class School(models.Model):
    name = models.CharField(max_length=256)
    principal = models.CharField(max_length=256)
    location = models.CharField(max_length=256)


    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('basic_app:detail',kwargs={'pk':self.pk})

class Student(models.Model):

    name = models.CharField(max_length=256)
    age = models.PositiveIntegerField()
    school = models.ForeignKey(School, related_name='students',on_delete=models.CASCADE)

    def __str__(self):
        return self.name
    

CBV/advcbv/basic_app/views.py
from typing import Any
from django.urls import reverse_lazy
from django.shortcuts import render
from django.views.generic import (View, TemplateView, ListView,DetailView, 
                                  CreateView, UpdateView, DeleteView)
from django.http import HttpResponse
from . import models

class IndexView(TemplateView):
    template_name = 'index.html'

class SchoolListView(ListView):
    model = models.School

class SchoolDetailView(DetailView):
    model = models.School
    template_name = 'basic_app/school_detail.html'
    context_object_name = 'school_detail'


class SchoolCreateView(CreateView):
    fields = ('name','principal','location')
    model = models.School


class SchoolUpdateView(UpdateView):
    fields = ('name','principal')
    model = models.School

class SchoolDeleteView(DeleteView):
    model = models.School
    success_url = reverse_lazy("basic_app:list")

CBV/advcbv/basic_app/templates/basic_app/basic_app_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <title>App Base</title>
</head>
<body>
    <nav class="navbar navbar-default navbar-static-top">
        <div class="nav navbar-nav">            
            <a class='navbar-brand'href="{% url 'basic_app:list' %}">Schools</a>
            <a class='navbar-link'href="{%url 'admin:index'%}">Admin</a>
        </div>
    </nav>

    {% block body_block %}
    {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</html>

CBV/advcbv/basic_app/templates/basic_app/school_confirm_delete.html
{% extends 'basic_app/basic_app_base.html' %}
{% block body_block %}
<h1>Delete {{school.name}}?</h1>
<form method="Post">
    {% csrf_token %}
    <input type="submit" value="Delete" class="btn  btn-danger">
    <a href="{% url 'basic_app:detail' pk=school.pk %}">Cancel</a>
</form>
{% endblock %}

CBV/advcbv/basic_app/templates/basic_app/school_detail.html
{% extends 'basic_app/basic_app_base.html'%}
{% block body_block%}
<div class="container">
    <h1>Welcome to the school detail page</h1>
    <h2>School Details:</h2>
    <p>Name: {{school_detail.name}}</p>
    <p>Principal: {{school_detail.principal}}</p>
    <p>Area: {{school_detail.location}}</p>

    <h3>Students</h3>
    {% for student in school_detail.students.all %}
    <p>{{student.name}} who is {{student.age}} years old</p>
    {% endfor %}
</div>

<div class="container">
    <p><a href="{% url 'basic_app:update' pk=school_detail.pk %}" class="btn btn-warning">Update</a></p>

</div>
{% endblock %}

CBV/advcbv/basic_app/templates/basic_app/school_form.html
{% extends 'basic_app/basic_app_base.html' %}
{% block body_block %}
    <h1>
        {% if not form.instance.pk %}
        Create School
        {% else %}
        Update School
        {% endif %}
    </h1>

    <form method="post">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit"  class="btn btn-primary" value="Submit" />
    </form>
{% endblock %}

CBV/advcbv/basic_app/templates/basic_app/school_list.html
{% extends "basic_app/basic_app_base.html" %}
{% block body_block %}
  <div class="jumbotron">

    <h1>Welcome to the List of Schools Page!</h1>
      <ol>
        {% for school in school_list %}
          <h2><li><a href="{{school.id}}/">{{school.name}} </a></li></h2>
        {% endfor %}
      </ol>

  </div>


{% endblock %}

CBV/advcbv/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <title>Base</title>
</head>
<body>
    <div class="container"></div>
    {%block body_block%}
    {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</html>

CBV/advcbv/templates/index.html
{% extends "base.html" %}
{% block body_block %}
<div class="jumbotron">
    <h1>Home Page!</h1>
</div>
{% endblock %}